### ISSUE TITLE
Package information before upload

### ISSUE THREAD

**Issue by theoriginalgri** [HSAnet/glimpse_distributor#21]
Currently the glimpse upload script decides which branches are uploaded to the distributor. This decision should be moved to the distributor.

One option would be to add a HEAD handler to the /upload url where the upload script tells its platform and branch (maybe more) information. Replies can be done with simple HTTP status codes (200 for "upload please").

Using this method, the distributor could maintain separate repositories for "release" and "development snapshot" builds.

**Comment by MKV21** [comment]
Fixed by https://github.com/HSAnet/glimpse_client/pull/261
